# Generated by Django 5.2.8 on 2025-11-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='category',
            new_name='category_id',
        ),
    ]
